### ISSUE TITLE
Resize windows?

### ISSUE THREAD

**Issue by Peter2121** [codic12/worm#36]
Hello, is there any way to resize application window in floating mode? It seems that windows do not have handlers to intercept mouse events on borders...

**Comment by codic12** [comment]
You can hold Alt while holding the right mouse button, and drag.
Or you can hold the right mouse button on the frame, and drag.

> intercept mouse events on borders...

I think that there is no way to do this with X11's inbuilt border functionality, but I'd love to be proven wrong if you have any tips. Otherwise in the future we can draw our own borders so that it can be resized from there.
