### ISSUE TITLE
Error loading shared library libXft

### ISSUE THREAD

**Issue by llamaWol** [codic12/worm#44]
I’m currently setting up worm on my laptop running void, and when trying to run the worm binary, im getting the error 

“could not load: libXft.so
(compile with -d:nimDebugDlOpen for more information)”

After being compiled with the option mentioned above, it cant load shared library libX11 and libXft, “No such file or directory”

I’m sure both libraries are installed, so I got no idea what it could be

**Comment by codic12** [comment]
You need the `libX11-devel` package on Void Linux.

Both libraries are installed on distributions which put them together (eg Arch), but Void, like Debian, doesn't include any development packages by default. Because the X11 bindings that Worm uses dynamically load libX11, they need the shared library.

Thanks for trying out worm!

**Comment by codic12** [comment]
You might also need libXft-devel.

**Comment by llamaWol** [comment]
Thanks a lot, that worked!
And thank you for creating the project, I like it a lot
