### ISSUE TITLE
Frame elements (title, buttons) do not rerender when unfocused

### ISSUE THREAD

**Issue by lambdadog** [codic12/worm#58]
This causes an "eraser" effect when dragging a window over them.

https://user-images.githubusercontent.com/36526063/162591302-fd23525b-fa24-4a81-858b-2f9bc529b2ff.mp4

**Comment by lambdadog** [comment]
Honestly I suspect the issue is perhaps less "windows don't rerender when unfocused" and moreso "the rerender that happens when a window is dragged only rerenders the window being dragged itself" but the effect is as so.

**Comment by lambdadog** [comment]
It's worth noting a compositor fixes this behavior but I'm of the opinion that it's still a bug regardless.

**Comment by codic12** [comment]
Partially fixed; you still get the "eraser" effect, but it's re-rendered on ButtonRelease (so when you let go of the mouse button). I don't know why this issue happens in the first place and why it only happens on certain windows; they shouldn't need to be re-rendered in the first place. But anyways, I think this is the best I can do for now until I get to the root cause.
