### ISSUE TITLE
Worm doesn't start

### ISSUE THREAD

**Issue by nixfreak** [codic12/worm#76]
I have tried using git repo and copying over the binaries to /usr/bin/ and chmod +x on both of them. 

I have tried using yay -S worm-git using xessions for sddm and lightdm. When I click on worm in the login manager I can only move the cursor. 

I have setup all the config files: 
/home/nixfreak/.config/worm
├── polybar
│   └── config.ini
├── rc
└── sxhkdrc

I have setup the same config file as in the examples to rc file. 

Nothing works , also I had to remove nim 1.6.1 version and devel because the build using yay wanted to install only 1.4. 
I nim on a daily basis and nimble. 

I am using an archinux x86-64 Linux chaosArch 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux
I have nimc version 
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0565a70eab02122ce278b98181c7d1170870865c
active boot switches: -d:release

If I could debug this why the executable isn't working I would , just no clue where to start.

**Comment by codic12** [comment]
> Nothing works , also I had to remove nim 1.6.1 version and devel because the build using yay wanted to install only 1.4.

No it just has the nim package from Arch as a dependency, which seems to be out of date. You can install another provider of the nim/nimble packages I guess...

Can you add a 
```
super + Return
   terminal
```
(replace terminal with any real terminal emulator) in sxhkdrc and see if it works? I think it's a configuration issue - for example, the root window is not changed probably because you dont have nitrogen installed and set up,, and the panel is not working because the polybar configuration is not working (to debug that run `polybar top -q -c ~/.config/worm/polybar/config.ini` from another environment, see if it works)

If this is not the case: can you run `worm` from the terminal in another environment and show the output? (It won't start it and will fail with BadAccess - that is expected behavior).

**Comment by nixfreak** [comment]
worm
19:36:42 | INFO | wm.nim:35 | Opened display
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  23
  Current serial number in output stream:  24

**Comment by nixfreak** [comment]
Ok good now , poly top doesn't exist , so I changed it and I can also open up kitty terminal and nitrogen works , thanks
